#ifndef HUMAN_DEFINES_HPP
#define HUMAN_DEFINES_HPP

#define HEAD_SCALE_X 0.1f
#define HEAD_SCALE_Y 0.1f
#define HEAD_SCALE_Z 0.1f

#define TORSO_SCALE_X 0.2f
#define TORSO_SCALE_Y 0.4f
#define TORSO_SCALE_Z 0.1f

#define RIGHT_ARM_SCALE_X 0.25f
#define RIGHT_ARM_SCALE_Y 0.04f
#define RIGHT_ARM_SCALE_Z 0.04f

#define RIGHT_LOWER_ARM_SCALE_X 0.2f
#define RIGHT_LOWER_ARM_SCALE_Y 0.025f
#define RIGHT_LOWER_ARM_SCALE_Z 0.025f

#define LEFT_ARM_SCALE_X 0.25f
#define LEFT_ARM_SCALE_Y 0.04f
#define LEFT_ARM_SCALE_Z 0.04f

#define LEFT_LOWER_ARM_SCALE_X 0.2f
#define LEFT_LOWER_ARM_SCALE_Y 0.025f
#define LEFT_LOWER_ARM_SCALE_Z 0.025f

#define RIGHT_LEG_SCALE_X 0.05f
#define RIGHT_LEG_SCALE_Y 0.2f
#define RIGHT_LEG_SCALE_Z 0.05f

#define RIGHT_LOWER_LEG_SCALE_X 0.035f
#define RIGHT_LOWER_LEG_SCALE_Y 0.2f
#define RIGHT_LOWER_LEG_SCALE_Z 0.035f

#define LEFT_LEG_SCALE_X 0.05f
#define LEFT_LEG_SCALE_Y 0.2f
#define LEFT_LEG_SCALE_Z 0.05f

#define LEFT_LOWER_LEG_SCALE_X 0.035f
#define LEFT_LOWER_LEG_SCALE_Y 0.2f
#define LEFT_LOWER_LEG_SCALE_Z 0.035f

#endif